### ISSUE TITLE
License for this project?

### ISSUE THREAD

**Issue by hiralsp** [colinmarc/sequencefile#11]
Hi,
the source tree doesn't contain a LICENSE or COPYING file, and none of the files have a copyright header. Who owns the copyright on this code and under what license is it being published?

Thanks :)

**Comment by hiralsp** [comment]
@colinmarc can you please add license

**Comment by jgill02** [comment]
Hi Colin and previous contributors,

I hope you all are well. I wanted to mention that from what I can tell, this is the only working public golang repository that solves the problem of opening + reading a sequencefile (and works flawlessly). I know in other repos you have added a MIT license (e.g. hdfs repo) - might it be possible to add a license to this repo? It would definitely be (yet another in your case ;p ) great contribution to the go community. 

If it would be helpful/make things easier I'd be happy to set up a PR for this similar to what your hdfs repo did.

Thank you for your consideration and apologies to revive a years-old thread!

Sincerely,

John

**Comment by colinmarc** [comment]
Sure, thanks for the ping. Fixed in e87732254f13756d6bb8e7e890b7f385b616675f

**Comment by jgill02** [comment]
Thank you SO MUCH!
